# Site settings
title: Kartik Chincholikar
email: fallingkartik@gmail.com
url: https://github.com/kartikchincholikar/kartikchincholikar.github.io
description: "Hey! I'm Kartik Chincholikar. I'm a Deep Learning professional with a love for communicating complex ideas in an easy manner"
keywords: "Kartik Chincholikar, Deep Learning, AI, Consultancy, Machine Learning, BootCamp, Teaching, "
skills: "Deep Learner - Teacher - Video Creator"
meta_author: Chincholikar Kartik

gem 'jekyll-sitemap'

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: 
  location: 
  social: Around the Web
  credits: 

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/KartikC14
  - title: youtube
    url: https://www.youtube.com/channel/UCq5hj2YogHzxCqqyjou2i8A
  - title: github
    url: https://github.com/kartikchincholikar

# Postal address (add as many lines as necessary)
address:
  - line: 
  - line: 

# Credits content
credits: 

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
